services:
  general-ledger:
    build:
      context: .
      dockerfile: hcau-general-ledger/Dockerfile
    profiles: ["apps"]
    ports:
      - "8081:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      PORT: 8080
    depends_on:
      - postgres
      - kafka
    networks:
      - ledger-net

  banking-reconcile:
    build:
      context: .
      dockerfile: hcau-banking-reconcile/Dockerfile
    profiles: ["apps"]
    ports:
      - "8082:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      PORT: 8080
    depends_on:
      - postgres
      - kafka
    networks:
      - ledger-net

  platform-service:
    build:
      context: .
      dockerfile: hcau-platform-service/Dockerfile
    profiles: ["apps"]
    ports:
      - "8083:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      PORT: 8080
    depends_on:
      - postgres
      - kafka
    networks:
      - ledger-net

networks:
  ledger-net:
    driver: bridge
