global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'general-ledger'
    static_configs:
      - targets: ['haicau-banking-general-ledger-1:8080']
    metrics_path: '/actuator/prometheus'

  - job_name: 'banking-reconcile'
    static_configs:
      - targets: ['haicau-banking-banking-reconcile-1:8080']
    metrics_path: '/actuator/prometheus'

  - job_name: 'platform-service'
    static_configs:
      - targets: ['haicau-banking-platform-service-1:8080']
    metrics_path: '/actuator/prometheus'
